apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.name }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin.password: {{ .Values.grafana.value | b64enc | quote }}
